use failure::Error;
use models::user::{User};

pub fn call(user: &User) -> Result<(), Error> {
	Ok(())
}
